### ISSUE TITLE
Broken.

### ISSUE THREAD

**Issue by 0xfffffff0075e2040** [XorTroll/Plutonium#1]
This is a gret thing, but somehow it only runned on hardware and the yuzu emulator gave me deeeep errors. would you mind fixing it for yuzu, so i can use this for further development test? thanks.

**Comment by XorTroll** [comment]
SDL2 cannot run on Yuzu

**Comment by 0xfffffff0075e2040** [comment]
fuce em. discording. I think you can pretty much close this now. but please say
"this is a mf closed file now. straight outta archive", k thx
