### ISSUE TITLE
There's a bug in elm_Button.cpp

### ISSUE THREAD

**Issue by wetor** [XorTroll/Plutonium#22]
`Button::Button(s32 X, s32 Y, s32 Width, s32 Height, String Content, Color TextColor, Color Color) `
about "TextColor" and "Color"

in the constructor:
```
        this->clr = Color;
        this->ntex = render::RenderText(this->fnt, Content, TextColor); 
```
and in Button::SetContent(String Content):
`        this->ntex = render::RenderText(this->fnt, Content, this->clr);`
This is an obvious mistake.

**Comment by XorTroll** [comment]
True, will correct it, thanks for pointing it out
