### ISSUE TITLE
Sample App Crashes

### ISSUE THREAD

**Issue by shyim** [XorTroll/Plutonium#3]
Hey,
i have compiled the sample app and the switch crashes and forces me to press the power button.

**Comment by XorTroll** [comment]
Which fw are you using?

**Comment by shyim** [comment]
5.1.0

**Comment by XorTroll** [comment]
Well, that's strange. I guess you built it with latest libnx, do you have everything updated from pacman?

**Comment by shyim** [comment]
Yep. It was the latest libnx

**Comment by XorTroll** [comment]
And latest SDL2?

**Comment by shyim** [comment]
I had all the latest packages from devkitpro :)

**Comment by XorTroll** [comment]
Maybe the sample fails on latest libnx, need to test it.
Anyone who can test this, please test it

**Comment by XorTroll** [comment]
New release should fix this
