### ISSUE TITLE
Latest lbnx is broken; Menu wont show up

### ISSUE THREAD

**Issue by 0d3n3h547v** [XorTroll/Plutonium#4]
switch-sdl2 or libnx are broken and gives me alot of warnings while i try to compile it.

Plus, in the main menu, you can see only the background. With the CustomUI Example, i tested it with a simple `if (keysDown & KEY_PLUS) return 0;` and is working

**Comment by XorTroll** [comment]
Ok, anyway these libs really need to be updated anyway

**Comment by XorTroll** [comment]
New release should fix this
