### ISSUE TITLE
Unable to link at compile

### ISSUE THREAD

**Issue by mrdude2478** [XorTroll/Plutonium#58]
I'm not sure what's causing this, but it doesn't work for me on windows or ubuntu. The program seems to compile and builds the elf file, but when linking it errors and the build fails. Here's the error:

linking tinwoo.elf
c:/msys64/opt/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld.exe: c:/msys64/opt/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld.exe: DWARF error: can't find .debug_ranges section.
C:/msys64/home/MrDude/switch/tinwoo/include/Plutonium/Plutonium/Output/lib\libpu.a(render_Renderer.o): in function `pu::ui::render::(anonymous namespace)::DoAddSharedFont(std::shared_ptr<pu::ttf::Font>&, PlSharedFontType)':
render_Renderer.cpp:(.text._ZN2pu2ui6render12_GLOBAL__N_115DoAddSharedFontERSt10shared_ptrINS_3ttf4FontEE16PlSharedFontType+0x64): undefined reference to `pu::ttf::Font::LoadFromMemory(void*, unsigned long, void (*)(void*))'
c:/msys64/opt/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/msys64/home/MrDude/switch/tinwoo/include/Plutonium/Plutonium/Output/lib\libpu.a(render_Renderer.o): in function `pu::ui::render::AddFontFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
render_Renderer.cpp:(.text._ZN2pu2ui6render11AddFontFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjS9_+0x50): undefined reference to `pu::ttf::Font::LoadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
c:/msys64/opt/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/msys64/home/MrDude/switch/tinwoo/include/Plutonium/Plutonium/Output/lib\libpu.a(render_Renderer.o): in function `void __gnu_cxx::new_allocator<pu::ttf::Font>::destroy<pu::ttf::Font>(pu::ttf::Font*)':
render_Renderer.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN2pu3ttf4FontEE7destroyIS3_EEvPT_[_ZN9__gnu_cxx13new_allocatorIN2pu3ttf4FontEE7destroyIS3_EEvPT_]+0x14): undefined reference to `pu::ttf::Font::~Font()'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /home/MrDude/switch/tinwoo/tinwoo.elf] Error 1
make: *** [Makefile:170: build] Error 2

**Comment by mrdude2478** [comment]
It seems to be an error in ttf_font.hpp at around line 70.

I commented out this:
//~Font();
//i32 LoadFromMemory(void *ptr, const size_t size, FontFaceDisposingFunction disp_fn);
//i32 LoadFromFile(const std::string &path);

And removed the reference to that in render_Renderer.cpp and then the app linked fine. Can you fix, thanks.

**Comment by XorTroll** [comment]
I'm pretty sure this has to do with your Makefile/setup, I've never faced this issue before

**Comment by mrdude2478** [comment]
OK thanks, I'll try and mod that.

**Comment by mrdude2478** [comment]
Thanks, you were right I managed to compile properly after fixing the old makefile I was using. I now have another question.

In the older version of this you could set the text block text size:

old
pu::ui::elm::TextBlock::New(10, 678, "test", 10);

New
pu::ui::elm::TextBlock::New(10, 678, "test");

In the new version this doesn't have the text size in the block - was reading the docs but I can't see the bit for changing the font size in them - do you have a hint you could share?

**Comment by XorTroll** [comment]
Now the expected behaviour is for you to create/load fonts with a certain size, then you can set the font on the TextBlock by SetFont(...)
Check Goldleaf's usage of this for more info, there are some default ones with different sizes

**Comment by mrdude2478** [comment]
Thanks, I had a look and see I can set it like this:

this->appVersionText = TextBlock::New(1210, 680, "v" + inst::config::appVersion);
this->appVersionText->SetColor(COLOR("#FFFFFFFF"));
this->appVersionText->SetFont(pu::ui::MakeDefaultFontName(10));

I've started modding tinwoo installer to work with the new plutonium and the current libnx and have done quite a bit of modding in the last few days, now I am having issues getting the touch screen working properly when an Item is selected it wasn't working so I had to disable that. Can you have a look in the ui files and let me know how to change the code so when I select an item in the menu's with touchscreen that will work the same as a button press?

If I do this, it doesn't execute the code in the block when touching the screen.
if ((Down & HidNpadButton_A) || (**Up &** HidGestureType_Touch)) {
//stuff  here
}

If I do this, It constantly executes the code in the block without touching the screen.
if ((Down & HidNpadButton_A) || (HidGestureType_Touch)) {
//stuff here
}

https://github.com/mrdude2478/TinWoo/tree/Test

**Comment by XorTroll** [comment]
This issue has drifted a lot from its original and already solved point.
I lack time to help you with/look into that, sorry

**Comment by mrdude2478** [comment]
Thanks, you're correct. Sorry - I solved the problem earlier today. Regards.
