### ISSUE TITLE
AddThread missing?

### ISSUE THREAD

**Issue by mrdude2478** [XorTroll/Plutonium#59]
In older plutonium before the rewrite in ui_layout there was a function in here:

<pu/ui/ui_Application.hpp> - void Application::AddThread(std::function<void()> Callback)
<pu/ui/ui_Layout.hpp> - void Layout::AddThread(std::function<void()> Callback)

I can't seem to find this in the new re-write, has this now been disabled, or is it hidden away somewhere? I can't find any equivalent in the docs.

Thanks.

**Comment by XorTroll** [comment]
Renamed to AddRenderCallback
