### ISSUE TITLE
Cannot display Chinese characters properly

### ISSUE THREAD

**Issue by rekcah1986** [XorTroll/Plutonium#8]
this->helloText = new pu::element::TextBlock(300, 300, "Hello 汉字测试!");

Got “Hello ⊠字⊠⊠!”

**Comment by rekcah1986** [comment]
And my system version is 6.2.0 and the language is "Simple Chinese / English"

**Comment by XorTroll** [comment]
Yeah, Plutonium renders in UTF-8. Would require to rewrite some things to unicode.

**Comment by rekcah1986** [comment]
So how to resolve it if I want to translate goldleaf？

**Comment by rekcah1986** [comment]
I changed to "\u6c49\u5b57\u6d4b\u8bd5", but it's still the same.

**Comment by XorTroll** [comment]
New pu::String handles UTF16 fine.
